# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       raleway-fonts

# >> macros
# << macros

Summary:    An elegant sans-serif typeface
Version:    3.0
Release:    1
Group:      System/Base
License:    OFL
BuildArch:  noarch
URL:        http://theleagueofmoveabletype.com/raleway
Source0:    %{name}-%{version}.tar.xz
Source100:  raleway-fonts.yaml
Requires:   fontpackages-filesystem
BuildRequires:  fontpackages-devel

%description
Raleway is an elegant sans-serif typeface, designed in a single thin weight.
It is a display face that features both old style and lining numerals,
standard and discretionary ligatures, a pretty complete set of diacritics,
as well as a stylistic alternate inspired by more geometric sans-serif
typefaces than its neo-grotesque inspired default character set.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
install -m 0755 -d %{buildroot}%{_fontconfig_templatedir} %{buildroot}%{_fontconfig_confdir}
ln -s %{_fontconfig_templatedir}/%{fontconf} %{buildroot}%{_fontconfig_confdir}/%{fontconf}
install -m 0644 -d -p "Raleway Thin.ttf" %{buildroot}%{_fontdir}/RalewayThin.ttf
# << install pre

# >> install post
# << install post

%_font_pkg -f %{fontconf} *.ttf
